[theme]
base = "light"
primaryColor = "#5046E4"
backgroundColor = "#F8F7F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1523"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
